# .github/workflows/publish.yml
name: Publish Package

on:
  workflow_run:
    workflows: ["Build", "Tests"]
    types:
      - completed

jobs:
  publish:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.ref == 'refs/heads/main' }}
    env:
      GITHUB_USERNAME: ${{ github.actor }}
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Set version
      run:
          printf "\nversion=${GITHUB_SHA::7}" >> gradle.properties

    - name: Publish package
      run: ./gradlew publish